# Generated by Django 4.2.4 on 2023-08-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(max_length=500, verbose_name="Amount")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "phoneNumber",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Phone number"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "businessName",
                    models.CharField(max_length=200, verbose_name="Business name"),
                ),
                (
                    "locationAddress",
                    models.CharField(max_length=200, verbose_name="Location address"),
                ),
                (
                    "emailAddress",
                    models.CharField(max_length=100, verbose_name="Email"),
                ),
                (
                    "phoneNumber",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Phone number"
                    ),
                ),
                ("password", models.CharField(max_length=50, verbose_name="Password")),
            ],
        ),
    ]
